version: '3'
services:
  database:
    image: 'postgres:latest'
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database
    volumes:
      - pgdb-data:/var/lib/postgresql/data/
    networks:
      - pg-net


networks:
  pg-net:

volumes:
  pgdb-data: