version: '3'
services:
  m183-totp:
    image: docker.io/3n3a/m183-totp:0.2.1
    depends_on:
      - postgres
    environment:
      - DATABASE_URL="postgres://postgres:postgres@host.docker.internal/"
      - ROCKET_SECRET_KEY="F/UXeFE3dNwSxXremOWc58c0J3AOWwOwSUdY78buKfk="
    ports:
      - 8007:8000
    networks:
      - pg-net

  postgres:
    image: 'postgres:latest'
    restart: "always"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database
    ports:
      - 5432:5432
    volumes:
      - pgdb-data:/var/lib/postgresql/data/
    networks:
      - pg-net


networks:
  pg-net:
    external: true

volumes:
  pgdb-data:
